# Generated by Django 4.2.2 on 2023-06-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='events',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
