# Generated by Django 4.2.3 on 2023-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_event_is_private_privatecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
