# Generated by Django 4.2.3 on 2023-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0005_alter_event_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tot_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rooms',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
