# Generated by Django 4.2.2 on 2023-06-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_participateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participateuser',
        ),
    ]
