# Generated by Django 4.2.2 on 2023-06-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_participateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participateuser',
        ),
    ]
