# Generated by Django 4.2.2 on 2023-06-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_participateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participateuser',
        ),
    ]
