# Generated by Django 4.2.2 on 2023-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_participateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateuser',
            name='rooms',
            field=models.CharField(max_length=50),
        ),
    ]
