# Generated by Django 4.2.2 on 2023-06-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_alter_participateuser_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participateuser',
        ),
    ]
