# Generated by Django 4.2.2 on 2023-06-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_participateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participateuser',
        ),
    ]
