# Generated by Django 4.2.3 on 2023-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_participateuser_new_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateuser',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
