# Generated by Django 4.2.3 on 2023-09-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_participateuser_is_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateuser',
            name='privatecode',
            field=models.TextField(default='', max_length=50),
        ),
    ]
